-- Forum community schema. Back up production before execution.
CREATE TABLE IF NOT EXISTS forum_sections (id BIGINT PRIMARY KEY AUTO_INCREMENT,name VARCHAR(40) NOT NULL,slug VARCHAR(60) NOT NULL UNIQUE,description VARCHAR(500),sort_order INT NOT NULL DEFAULT 0,status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL);
CREATE TABLE IF NOT EXISTS forum_posts (id BIGINT PRIMARY KEY AUTO_INCREMENT,section_id BIGINT NOT NULL,author_id BIGINT NOT NULL,title VARCHAR(120) NOT NULL,content TEXT NOT NULL,image_urls TEXT,tags VARCHAR(500),status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',like_count INT NOT NULL DEFAULT 0,comment_count INT NOT NULL DEFAULT 0,favorite_count INT NOT NULL DEFAULT 0,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,CONSTRAINT fk_forum_posts_section FOREIGN KEY(section_id) REFERENCES forum_sections(id),CONSTRAINT fk_forum_posts_author FOREIGN KEY(author_id) REFERENCES users(id));
CREATE TABLE IF NOT EXISTS forum_comments (id BIGINT PRIMARY KEY AUTO_INCREMENT,post_id BIGINT NOT NULL,author_id BIGINT NOT NULL,content TEXT NOT NULL,status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,CONSTRAINT fk_forum_comments_post FOREIGN KEY(post_id) REFERENCES forum_posts(id),CONSTRAINT fk_forum_comments_author FOREIGN KEY(author_id) REFERENCES users(id));
CREATE TABLE IF NOT EXISTS forum_post_likes (id BIGINT PRIMARY KEY AUTO_INCREMENT,post_id BIGINT NOT NULL,user_id BIGINT NOT NULL,created_at DATETIME NOT NULL,CONSTRAINT uk_forum_like_post_user UNIQUE(post_id,user_id),CONSTRAINT fk_forum_likes_post FOREIGN KEY(post_id) REFERENCES forum_posts(id),CONSTRAINT fk_forum_likes_user FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE IF NOT EXISTS forum_post_favorites (id BIGINT PRIMARY KEY AUTO_INCREMENT,post_id BIGINT NOT NULL,user_id BIGINT NOT NULL,created_at DATETIME NOT NULL,CONSTRAINT uk_forum_favorite_post_user UNIQUE(post_id,user_id),CONSTRAINT fk_forum_favorites_post FOREIGN KEY(post_id) REFERENCES forum_posts(id),CONSTRAINT fk_forum_favorites_user FOREIGN KEY(user_id) REFERENCES users(id));
CREATE INDEX idx_forum_sections_status_sort ON forum_sections(status,sort_order);
CREATE INDEX idx_forum_posts_section_status_created ON forum_posts(section_id,status,created_at);
CREATE INDEX idx_forum_posts_status_hot ON forum_posts(status,like_count,comment_count);
CREATE INDEX idx_forum_comments_post_status_created ON forum_comments(post_id,status,created_at);
INSERT INTO forum_sections(name,slug,description,sort_order,status,created_at,updated_at) SELECT '姹傝亴浜ゆ祦','job-search','姹傝亴淇℃伅鍜岀粡楠屼氦娴?,1,'ACTIVE',NOW(),NOW() WHERE NOT EXISTS(SELECT 1 FROM forum_sections WHERE slug='job-search');
INSERT INTO forum_sections(name,slug,description,sort_order,status,created_at,updated_at) SELECT '鑱屽満缁忛獙','workplace','鑱屽満鎴愰暱涓庣粡楠屽垎浜?,2,'ACTIVE',NOW(),NOW() WHERE NOT EXISTS(SELECT 1 FROM forum_sections WHERE slug='workplace');
INSERT INTO forum_sections(name,slug,description,sort_order,status,created_at,updated_at) SELECT '闈㈣瘯缁忛獙','interview','闈㈣瘯鎶€宸у拰澶嶇洏浜ゆ祦',3,'ACTIVE',NOW(),NOW() WHERE NOT EXISTS(SELECT 1 FROM forum_sections WHERE slug='interview');
INSERT INTO forum_sections(name,slug,description,sort_order,status,created_at,updated_at) SELECT '鐢熸椿闂茶亰','life','杞绘澗浜ゆ祦鍜岀敓娲诲垎浜?,4,'ACTIVE',NOW(),NOW() WHERE NOT EXISTS(SELECT 1 FROM forum_sections WHERE slug='life');

